#pragma once


const auto clcc_io = 
"CSCANI         ST          R7, CIOR7\n"
"               ST          R1, CIOR1\n"
"               ST          R2, CIOR2\n"
"               ST          R3, CIOR3\n"
"               LD          R1, CSCANBEGINPTR\n"
"               LD          R7, CSCANENDPTR\n"
"               NOT         R7, R7\n"
"               ADD         R7, R7, #1\n"
"               ADD         R7, R7, R1\n"
"               BRnp        CSCANIGETI\n"
"               JSR         CSCAN\n"
"               LD          R1, CSCANBEGINPTR\n"
"CSCANIGETI     AND         R0, R0, #0\n"
"               LD          R2, CLRANGE\n"
"CGETILOOP      LDR         R7, R1, #0\n"
"               ADD         R7, R7, R2\n"
"               BRn         CGETIFINISH\n"
"               ADD         R3, R7, #-9\n"
"               BRp         CGETIFINISH\n"
"               ADD         R7, R7, R0\n"
"               ADD         R7, R7, R0\n"
"               ADD         R0, R0, R0\n"
"               ADD         R0, R0, R0\n"
"               ADD         R0, R0, R0\n"
"               ADD         R0, R0, R7    ;   x10\n"
"               ADD         R1, R1, #1\n"
"               BR          CGETILOOP\n"
"CGETIFINISH    ST          R1, CSCANBEGINPTR\n"
"               LD          R7, CIOR7\n"
"               LD          R1, CIOR1\n"
"               LD          R2, CIOR2\n"
"               LD          R3, CIOR3\n"
"               RET\n"

"CLRANGE        .FILL       #-48\n"

"CSCANC         ST          R7, CIOR7\n"
"               ST          R1, CIOR1\n"
"               LD          R1, CSCANBEGINPTR\n"
"               LD          R7, CSCANENDPTR\n"
"               NOT         R7, R7\n"
"               ADD         R7, R7, #1\n"
"               ADD         R7, R7, R1\n"
"               BRnp        CSCANCGETC\n"
"               JSR         CSCAN\n"
"               LD          R1, CSCANBEGINPTR\n"
"CSCANCGETC     LDR         R0, R1, #0\n"
"               ADD         R1, R1, #1\n"
"               ST          R1, CSCANBEGINPTR\n"
"               LD          R7, CIOR7\n"
"               LD          R1, CIOR1\n"
"               RET\n"

"CIOR7          .BLKW       1\n"
"CIOR1          .BLKW       1\n"
"CIOR2          .BLKW       1\n"
"CIOR3          .BLKW       1\n"

"CSCANPTR       .FILL       CSCANBUF\n"
"CSCANBEGINPTR  .FILL       CSCANBUF\n"
"CSCANENDPTR    .FILL       CSCANBUF\n"

"CSCAN          ST          R7, CSCANR7\n"
"               ST          R1, CSCANR1\n"
"               LD          R1, CSCANPTR\n"
"CWAIT          LDI         R0, CCANSCAN   ; Wait until input\n"
"               BRzp        CWAIT\n"
"               LDI         R0, CSRCPTR\n"
"               ADD         R7, R0, #-10\n"
"               BRz         CSCANGET\n"
"               TRAP        x21\n"
"               STR         R0, R1, #0\n"
"               ADD         R1, R1, #1\n"
"               BR          CWAIT\n"
"CSCANGET       AND         R7, R7, #0\n"
"               STR         R7, R1, #0\n"
"               ST          R1, CSCANENDPTR\n"
"               LD          R1, CSCANPTR\n"
"               ST          R1, CSCANBEGINPTR\n"
"               AND         R0, R0, #0\n"
"               ADD         R0, R0, #10\n"
"               TRAP        x21\n"
"               LD          R7, CSCANR7\n"
"               LD          R1, CSCANR1\n"
"               RET\n"
"CCANSCAN       .FILL       xFE00\n"
"CSRCPTR        .FILL       xFE02\n"
"CSCANR7        .BLKW       1\n"
"CSCANR1        .BLKW       1\n"

"CSCANBUF       .BLKW       x301\n"

"CPRINTI        ST          R7, CPRR7\n"
"               ST          R1, CPRR1\n"
"               ST          R2, CPRR2\n"
"               AND         R2, R2, #0\n"
"               ADD         R1, R0, #0\n"
"               BRp         CPPRINT4\n"
"               BRn         CPPRINTREV\n"
"               LD          R0, CIBASCII\n"
"               TRAP        x21\n"
"               BR          CPPRINTFINISH\n"
"CPPRINTREV     NOT         R1, R1\n"
"               LD          R0, CIBSGN\n"
"               TRAP        x21\n"
"               ADD         R1, R1, #1\n"

"CPPRINT4       AND         R0, R0, #0\n"
"               LD          R7, CIBIT4\n"
"CPPRINT4N      ADD         R1, R7, R1\n"
"               BRn         CPPRINT3\n"
"               ADD         R0, R0, #1\n"
"               BR          CPPRINT4N\n"

"CPPRINT3       LD          R7, CIRBIT4\n"
"               ADD         R1, R1, R7\n"
"               ADD         R2, R0, #0\n"
"               BRnz        CPPRINT3Y\n"
"               LD          R7, CIBASCII\n"
"               ADD         R0, R0, R7\n"
"               TRAP        x21\n"
"CPPRINT3Y      LD          R7, CIBIT3\n"
"               AND         R0, R0, #0\n"
"CPPRINT3N      ADD         R1, R7, R1\n"
"               BRn         CPPRINT2\n"
"               ADD         R0, R0, #1\n"
"               BR          CPPRINT3N\n"

"CPPRINT2       LD          R7, CIRBIT3\n"
"               ADD         R1, R1, R7\n"
"               ADD         R2, R0, #0\n"
"               BRnz        CPPRINT2Y\n"
"               LD          R7, CIBASCII\n"
"               ADD         R0, R0, R7\n"
"               TRAP        x21\n"
"CPPRINT2Y      LD          R7, CIBIT2\n"
"               AND         R0, R0, #0\n"
"CPPRINT2N      ADD         R1, R7, R1\n"
"               BRn         CPPRINT1\n"
"               ADD         R0, R0, #1\n"
"               BR          CPPRINT2N\n"

"CPPRINT1       LD          R7, CIRBIT2\n"
"               ADD         R1, R1, R7\n"
"               ADD         R2, R0, #0\n"
"               BRnz        CPPRINT1Y\n"
"               LD          R7, CIBASCII\n"
"               ADD         R0, R0, R7\n"
"               TRAP        x21\n"
"CPPRINT1Y      LD          R7, CIBIT1\n"
"               AND         R0, R0, #0\n"
"CPPRINT1N      ADD         R1, R7, R1\n"
"               BRn         CPPRINT0\n"
"               ADD         R0, R0, #1\n"
"               BR          CPPRINT1N\n"

"CPPRINT0       ADD         R1, R1, #10\n"
"               ADD         R2, R0, #0\n"
"               BRnz        CPP0\n"
"               LD          R7, CIBASCII\n"
"               ADD         R0, R0, R7\n"
"               TRAP        x21\n"
"CPP0           LD          R7, CIBASCII\n"
"               ADD         R0, R1, R7\n"
"               TRAP        x21\n"

"CPPRINTFINISH  LD          R7, CPRR7\n"
"               LD          R1, CPRR1\n"
"               LD          R2, CPRR2\n"
"               RET\n"
"CPRR7          .BLKW       #1\n"
"CPRR1          .BLKW       #1\n"
"CPRR2          .BLKW       #1\n"

"CIBASCII       .FILL       #48\n"   
"CIBSGN         .FILL       #45\n"
"CIBIT4         .FILL       #-10000\n"
"CIBIT3         .FILL       #-1000\n"
"CIBIT2         .FILL       #-100\n"
"CIBIT1         .FILL       #-10\n"
"CIRBIT4        .FILL       #10000\n"
"CIRBIT3        .FILL       #1000\n"
"CIRBIT2        .FILL       #100\n"
"CIRBIT1        .FILL       #10\n"

;

/*
const auto clcc_scand = 
"CSCAND         ST, R7, CSCANDR7\n"
"";*/
